AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template for CloudFront, Application Load Balancer, and EC2 instance"

Resources:
  MyLoadBalancer:
    Type: "AWS::ElasticLoadBalancingV2::LoadBalancer"
    Properties:
      Name: "myloadbalancer"
      Scheme: "internet-facing"
      LoadBalancerAttributes:
        - Key: "access_logs.s3.enabled"
          Value: "false"
      Subnets:
        - "subnet-07035e410d6f5aa6c"
        - "subnet-0acc453cd9499d87c"
        - "subnet-0674d53b09bfb3e08"
      SecurityGroups:
        - "sg-0e90ee0fa811c69f5"
        - "sg-08b7e064c7950eea8"
      Tags:
        - Key: "Name"
          Value: "myloadbalancer"

  MyTargetGroup:
    Type: "AWS::ElasticLoadBalancingV2::TargetGroup"
    Properties:
      Name: "mytargetgroup"
      Port: 8080
      Protocol: "HTTP"
      VpcId: "vpc-0e2bd8053ed0a4d1e"
      HealthCheckPath: "/"
      HealthCheckPort: "8080"
      HealthCheckProtocol: "HTTP"
      Matcher:
        HttpCode: "200-399"
      TargetType: "instance"

  MyListener:
    Type: "AWS::ElasticLoadBalancingV2::Listener"
    Properties:
      DefaultActions:
        - Type: "forward"
          TargetGroupArn: "arn:aws:elasticloadbalancing:us-east-1:724975761278:targetgroup/mytargetgroup/29bc891720570ab1"
      LoadBalancerArn: "arn:aws:elasticloadbalancing:us-east-1:724975761278:loadbalancer/app/myloadbalancer/8964edbbbfd16d15"
      Port: 80
      Protocol: "HTTP"

  MySecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: "Security group for my EC2 instance"
      SecurityGroupIngress:
        - CidrIp: "0.0.0.0/0"
          IpProtocol: "tcp"
          FromPort: 80
          ToPort: 80
      VpcId: "vpc-0e2bd8053ed0a4d1e"

  MyInstance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: "t2.micro"
      ImageId: "ami-079db87dc4c10ac91" 
      SecurityGroupIds:
        - "sg-08b7e064c7950eea8"
      SubnetId: "subnet-07035e410d6f5aa6c"
      Tags:
        - Key: "Name"
          Value: "myserver"